[package]
name = "pdfexporter"
version = "0.1.0"
edition = "2021"
authors = ["Lachugin pinkyGoose Vladimir"]

[dependencies]

headless_chrome = "1.0.10"
libc = "0.2.155"

[build-dependencies]
cbindgen = "0.26.0"

[lib]
name = "pdfexporter"
crate-type = ["cdylib"]